version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bukalapak/ottoman
    docker:
      - image: circleci/golang:1.10-stretch
      - image: bitnami/redis:5.0
        environment:
          ALLOW_EMPTY_PASSWORD: 'yes'
      - image: memcached:1.4-alpine
      - image: grokzen/redis-cluster:5.0.4
      - image: bitnami/redis-sentinel:5.0
        environment:
          REDIS_HOST_MASTER: 'localhost'
          REDIS_MASTER_SET: 'redis-master'
    steps:
      - checkout
      - run: go version
      - run: go get -t ./...
      - run: make check
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)

