version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bukalapak/ottoman
    docker:
      - image: circleci/golang:1.12-stretch
      - image: memcached:1.4-alpine
      - image: bitnami/redis:5.0
        environment:
          ALLOW_EMPTY_PASSWORD: 'yes'
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install redis-server
      - run:
          command: redis-server .circleci/sentinel.conf --sentinel
          background: true
      - run: go version
      - run: go get -t ./...
      - run: make check
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)

